// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FileUploader: typeof import('C:/Users/Administrator/Documents/Projects/Personal/marker-js-test/src/components/FileUploader.vue')['default']
    HelloWorld: typeof import('C:/Users/Administrator/Documents/Projects/Personal/marker-js-test/src/components/HelloWorld.vue')['default']
    ImageMarker: typeof import('C:/Users/Administrator/Documents/Projects/Personal/marker-js-test/src/components/ImageMarker.vue')['default']
    MarkersPanel: typeof import('C:/Users/Administrator/Documents/Projects/Personal/marker-js-test/src/components/MarkersPanel.vue')['default']
  }
}

export { }
